// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/forgot-password": {
            "post": {
                "description": "Request a password reset token for an email address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Forgot password",
                "parameters": [
                    {
                        "description": "Forgot password payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.forgotPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/auth.forgotPasswordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate a user and return an access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.loginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Create a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "Register payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.registerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/episodes": {
            "get": {
                "description": "List all episodes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "episodes"
                ],
                "summary": "List episodes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/episode.episodeResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new episode record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "episodes"
                ],
                "summary": "Create episode",
                "parameters": [
                    {
                        "description": "Episode payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/episode.createEpisodeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/episode.episodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/episodes/{internalEpisodeId}": {
            "get": {
                "description": "Get an episode by internal episode id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "episodes"
                ],
                "summary": "Get episode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Internal episode UUID",
                        "name": "internalEpisodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/episode.episodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an episode by internal episode id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "episodes"
                ],
                "summary": "Update episode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Internal episode UUID",
                        "name": "internalEpisodeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Episode payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/episode.updateEpisodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/episode.episodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an episode by internal episode id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "episodes"
                ],
                "summary": "Delete episode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Internal episode UUID",
                        "name": "internalEpisodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Service liveness endpoint",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.healthResponse"
                        }
                    }
                }
            }
        },
        "/metadata/search": {
            "get": {
                "description": "Search metadata by provider type (anidb default, tvdb optional)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metadata"
                ],
                "summary": "Metadata search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Provider type: anidb|tvdb (default anidb)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/metadata.SearchHitResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/metadata/show": {
            "post": {
                "description": "Create a show and enqueue a job_shows record linked to the show",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metadata"
                ],
                "summary": "Add show from metadata search item",
                "parameters": [
                    {
                        "description": "Search show item payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/metadata.AddShowRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/metadata.AddShowResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/shows": {
            "get": {
                "description": "List all shows",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shows"
                ],
                "summary": "List shows",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/show.showResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new show record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shows"
                ],
                "summary": "Create show",
                "parameters": [
                    {
                        "description": "Show payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/show.createShowRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/show.showResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/shows/{internalShowId}": {
            "get": {
                "description": "Get a show by internal show id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shows"
                ],
                "summary": "Get show",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Internal show UUID",
                        "name": "internalShowId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/show.showResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a show by internal show id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shows"
                ],
                "summary": "Update show",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Internal show UUID",
                        "name": "internalShowId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Show payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/show.updateShowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/show.showResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a show by internal show id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shows"
                ],
                "summary": "Delete show",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Internal show UUID",
                        "name": "internalShowId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperr.APIErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.forgotPasswordRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "auth.forgotPasswordResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "auth.loginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.loginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "token_type": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/auth.userResponse"
                }
            }
        },
        "auth.registerRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.registerResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/auth.userResponse"
                }
            }
        },
        "auth.userResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "episode.createEpisodeRequest": {
            "type": "object",
            "properties": {
                "airDate": {
                    "type": "string"
                },
                "episodeNumber": {
                    "type": "integer"
                },
                "externalIds": {
                    "$ref": "#/definitions/episode.externalIDs"
                },
                "runtimeMinutes": {
                    "type": "integer"
                },
                "seasonNumber": {
                    "type": "integer"
                },
                "showId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "episode.episodeResponse": {
            "type": "object",
            "properties": {
                "airDate": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "episodeNumber": {
                    "type": "integer"
                },
                "externalIds": {
                    "$ref": "#/definitions/episode.externalIDs"
                },
                "internalEpisodeId": {
                    "type": "string"
                },
                "runtimeMinutes": {
                    "type": "integer"
                },
                "seasonNumber": {
                    "type": "integer"
                },
                "showId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "episode.externalIDs": {
            "type": "object",
            "properties": {
                "anilist": {
                    "type": "integer"
                },
                "tvdb": {
                    "type": "integer"
                }
            }
        },
        "episode.updateEpisodeRequest": {
            "type": "object",
            "properties": {
                "airDate": {
                    "type": "string"
                },
                "episodeNumber": {
                    "type": "integer"
                },
                "externalIds": {
                    "$ref": "#/definitions/episode.externalIDs"
                },
                "runtimeMinutes": {
                    "type": "integer"
                },
                "seasonNumber": {
                    "type": "integer"
                },
                "showId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "http.healthResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "httperr.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "httperr.APIErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/httperr.APIError"
                }
            }
        },
        "metadata.AddShowRequest": {
            "type": "object",
            "properties": {
                "altTitles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "bannerUrl": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "episodeCount": {
                    "type": "integer"
                },
                "externalId": {
                    "type": "string"
                },
                "posterUrl": {
                    "type": "string"
                },
                "seasonCount": {
                    "type": "integer"
                },
                "startDate": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "synopsis": {
                    "type": "string"
                },
                "titleOriginal": {
                    "type": "string"
                },
                "titlePreferred": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "metadata.AddShowResponse": {
            "type": "object",
            "properties": {
                "internalJobShowId": {
                    "type": "string"
                },
                "internalShowId": {
                    "type": "string"
                },
                "retryCount": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "metadata.SearchHitResponse": {
            "type": "object",
            "properties": {
                "altTitles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "bannerUrl": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "episodeCount": {
                    "type": "integer"
                },
                "externalId": {
                    "type": "string"
                },
                "posterUrl": {
                    "type": "string"
                },
                "seasonCount": {
                    "type": "integer"
                },
                "startDate": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "synopsis": {
                    "type": "string"
                },
                "titleOriginal": {
                    "type": "string"
                },
                "titlePreferred": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "show.createShowRequest": {
            "type": "object",
            "properties": {
                "altTitles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "bannerUrl": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "episodeCount": {
                    "type": "integer"
                },
                "externalId": {
                    "type": "string"
                },
                "posterUrl": {
                    "type": "string"
                },
                "seasonCount": {
                    "type": "integer"
                },
                "startDate": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "synopsis": {
                    "type": "string"
                },
                "titleOriginal": {
                    "type": "string"
                },
                "titlePreferred": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "show.showResponse": {
            "type": "object",
            "properties": {
                "altTitles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "bannerUrl": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "episodeCount": {
                    "type": "integer"
                },
                "externalId": {
                    "type": "string"
                },
                "internalShowId": {
                    "type": "string"
                },
                "posterUrl": {
                    "type": "string"
                },
                "seasonCount": {
                    "type": "integer"
                },
                "startDate": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "synopsis": {
                    "type": "string"
                },
                "titleOriginal": {
                    "type": "string"
                },
                "titlePreferred": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "show.updateShowRequest": {
            "type": "object",
            "properties": {
                "altTitles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "bannerUrl": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "episodeCount": {
                    "type": "integer"
                },
                "externalId": {
                    "type": "string"
                },
                "posterUrl": {
                    "type": "string"
                },
                "seasonCount": {
                    "type": "integer"
                },
                "startDate": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "synopsis": {
                    "type": "string"
                },
                "titleOriginal": {
                    "type": "string"
                },
                "titlePreferred": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Bisky API",
	Description:      "API for Bisky",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
