// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_orgs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGithubOrg = `-- name: CreateGithubOrg :one
INSERT INTO github_orgs (name, external_org_id)
VALUES ($1, $2)
RETURNING id, name, external_org_id, created_at, updated_at
`

type CreateGithubOrgParams struct {
	Name          string
	ExternalOrgID pgtype.Int8
}

func (q *Queries) CreateGithubOrg(ctx context.Context, arg CreateGithubOrgParams) (GithubOrg, error) {
	row := q.db.QueryRow(ctx, createGithubOrg, arg.Name, arg.ExternalOrgID)
	var i GithubOrg
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalOrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGithubOrg = `-- name: DeleteGithubOrg :exec
DELETE FROM github_orgs
WHERE id = $1
`

func (q *Queries) DeleteGithubOrg(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGithubOrg, id)
	return err
}

const getGithubOrgByID = `-- name: GetGithubOrgByID :one
SELECT id, name, external_org_id, created_at, updated_at
FROM github_orgs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetGithubOrgByID(ctx context.Context, id string) (GithubOrg, error) {
	row := q.db.QueryRow(ctx, getGithubOrgByID, id)
	var i GithubOrg
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalOrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGithubOrgs = `-- name: ListGithubOrgs :many
SELECT id, name, external_org_id, created_at, updated_at
FROM github_orgs
ORDER BY created_at DESC
`

func (q *Queries) ListGithubOrgs(ctx context.Context) ([]GithubOrg, error) {
	rows, err := q.db.Query(ctx, listGithubOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubOrg
	for rows.Next() {
		var i GithubOrg
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExternalOrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGithubOrg = `-- name: UpdateGithubOrg :one
UPDATE github_orgs
SET
  name = $2,
  external_org_id = $3,
  updated_at = now()
WHERE id = $1
RETURNING id, name, external_org_id, created_at, updated_at
`

type UpdateGithubOrgParams struct {
	ID            string
	Name          string
	ExternalOrgID pgtype.Int8
}

func (q *Queries) UpdateGithubOrg(ctx context.Context, arg UpdateGithubOrgParams) (GithubOrg, error) {
	row := q.db.QueryRow(ctx, updateGithubOrg, arg.ID, arg.Name, arg.ExternalOrgID)
	var i GithubOrg
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalOrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
