// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type GithubOrg struct {
	ID            string
	Name          string
	ExternalOrgID pgtype.Int8
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Pat struct {
	ID             string
	Name           string
	TokenEncrypted string
	TokenLast4     string
	Scope          string
	GithubOrgID    *string
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Repo struct {
	ID             string
	Org            string
	Name           string
	GithubID       pgtype.Int8
	HtmlUrl        *string
	Description    *string
	IsPrivate      bool
	DefaultBranch  string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UserID         *string
	RepoCategoryID *string
	GithubOrgID    *string
}

type RepoCategory struct {
	ID          string
	Name        string
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
