// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pats.sql

package sqlc

import (
	"context"
)

const createPAT = `-- name: CreatePAT :one
INSERT INTO pats (name, token_encrypted, token_last4, scope, github_org_id, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, token_encrypted, token_last4, scope, github_org_id, is_active, created_at, updated_at
`

type CreatePATParams struct {
	Name           string
	TokenEncrypted string
	TokenLast4     string
	Scope          string
	GithubOrgID    *string
	IsActive       bool
}

func (q *Queries) CreatePAT(ctx context.Context, arg CreatePATParams) (Pat, error) {
	row := q.db.QueryRow(ctx, createPAT,
		arg.Name,
		arg.TokenEncrypted,
		arg.TokenLast4,
		arg.Scope,
		arg.GithubOrgID,
		arg.IsActive,
	)
	var i Pat
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenEncrypted,
		&i.TokenLast4,
		&i.Scope,
		&i.GithubOrgID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePAT = `-- name: DeletePAT :exec
DELETE FROM pats
WHERE id = $1
`

func (q *Queries) DeletePAT(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePAT, id)
	return err
}

const getPATByID = `-- name: GetPATByID :one
SELECT id, name, token_encrypted, token_last4, scope, github_org_id, is_active, created_at, updated_at
FROM pats
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPATByID(ctx context.Context, id string) (Pat, error) {
	row := q.db.QueryRow(ctx, getPATByID, id)
	var i Pat
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenEncrypted,
		&i.TokenLast4,
		&i.Scope,
		&i.GithubOrgID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPATs = `-- name: ListPATs :many
SELECT id, name, token_encrypted, token_last4, scope, github_org_id, is_active, created_at, updated_at
FROM pats
ORDER BY created_at DESC
`

func (q *Queries) ListPATs(ctx context.Context) ([]Pat, error) {
	rows, err := q.db.Query(ctx, listPATs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pat
	for rows.Next() {
		var i Pat
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenEncrypted,
			&i.TokenLast4,
			&i.Scope,
			&i.GithubOrgID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePAT = `-- name: UpdatePAT :one
UPDATE pats
SET
  name = $2,
  token_encrypted = $3,
  token_last4 = $4,
  scope = $5,
  github_org_id = $6,
  is_active = $7,
  updated_at = now()
WHERE id = $1
RETURNING id, name, token_encrypted, token_last4, scope, github_org_id, is_active, created_at, updated_at
`

type UpdatePATParams struct {
	ID             string
	Name           string
	TokenEncrypted string
	TokenLast4     string
	Scope          string
	GithubOrgID    *string
	IsActive       bool
}

func (q *Queries) UpdatePAT(ctx context.Context, arg UpdatePATParams) (Pat, error) {
	row := q.db.QueryRow(ctx, updatePAT,
		arg.ID,
		arg.Name,
		arg.TokenEncrypted,
		arg.TokenLast4,
		arg.Scope,
		arg.GithubOrgID,
		arg.IsActive,
	)
	var i Pat
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenEncrypted,
		&i.TokenLast4,
		&i.Scope,
		&i.GithubOrgID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
