// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repo_categories.sql

package sqlc

import (
	"context"
)

const createRepoCategory = `-- name: CreateRepoCategory :one
INSERT INTO repo_categories (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateRepoCategoryParams struct {
	Name        string
	Description *string
}

func (q *Queries) CreateRepoCategory(ctx context.Context, arg CreateRepoCategoryParams) (RepoCategory, error) {
	row := q.db.QueryRow(ctx, createRepoCategory, arg.Name, arg.Description)
	var i RepoCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepoCategory = `-- name: DeleteRepoCategory :exec
DELETE FROM repo_categories
WHERE id = $1
`

func (q *Queries) DeleteRepoCategory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRepoCategory, id)
	return err
}

const getRepoCategoryByID = `-- name: GetRepoCategoryByID :one
SELECT id, name, description, created_at, updated_at
FROM repo_categories
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRepoCategoryByID(ctx context.Context, id string) (RepoCategory, error) {
	row := q.db.QueryRow(ctx, getRepoCategoryByID, id)
	var i RepoCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepoCategories = `-- name: ListRepoCategories :many
SELECT id, name, description, created_at, updated_at
FROM repo_categories
ORDER BY created_at DESC
`

func (q *Queries) ListRepoCategories(ctx context.Context) ([]RepoCategory, error) {
	rows, err := q.db.Query(ctx, listRepoCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoCategory
	for rows.Next() {
		var i RepoCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepoCategory = `-- name: UpdateRepoCategory :one
UPDATE repo_categories
SET
  name = $2,
  description = $3,
  updated_at = now()
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateRepoCategoryParams struct {
	ID          string
	Name        string
	Description *string
}

func (q *Queries) UpdateRepoCategory(ctx context.Context, arg UpdateRepoCategoryParams) (RepoCategory, error) {
	row := q.db.QueryRow(ctx, updateRepoCategory, arg.ID, arg.Name, arg.Description)
	var i RepoCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
