// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shows.sql

package sqlc

import (
	"context"
)

const createShow = `-- name: CreateShow :one
INSERT INTO shows (
  title_preferred,
  title_original,
  alt_titles,
  type,
  status,
  synopsis,
  start_date,
  end_date,
  poster_url,
  banner_url,
  season_count,
  episode_count,
  external_ids
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING
  internal_show_id,
  title_preferred,
  title_original,
  alt_titles,
  type,
  status,
  synopsis,
  start_date,
  end_date,
  poster_url,
  banner_url,
  season_count,
  episode_count,
  external_ids,
  created_at,
  updated_at
`

type CreateShowParams struct {
	TitlePreferred string
	TitleOriginal  *string
	AltTitles      []string
	Type           string
	Status         string
	Synopsis       *string
	StartDate      *string
	EndDate        *string
	PosterUrl      *string
	BannerUrl      *string
	SeasonCount    *int64
	EpisodeCount   *int64
	ExternalIds    []byte
}

func (q *Queries) CreateShow(ctx context.Context, arg CreateShowParams) (Show, error) {
	row := q.db.QueryRow(ctx, createShow,
		arg.TitlePreferred,
		arg.TitleOriginal,
		arg.AltTitles,
		arg.Type,
		arg.Status,
		arg.Synopsis,
		arg.StartDate,
		arg.EndDate,
		arg.PosterUrl,
		arg.BannerUrl,
		arg.SeasonCount,
		arg.EpisodeCount,
		arg.ExternalIds,
	)
	var i Show
	err := row.Scan(
		&i.InternalShowID,
		&i.TitlePreferred,
		&i.TitleOriginal,
		&i.AltTitles,
		&i.Type,
		&i.Status,
		&i.Synopsis,
		&i.StartDate,
		&i.EndDate,
		&i.PosterUrl,
		&i.BannerUrl,
		&i.SeasonCount,
		&i.EpisodeCount,
		&i.ExternalIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShow = `-- name: DeleteShow :one
DELETE FROM shows
WHERE internal_show_id = $1::uuid
RETURNING internal_show_id
`

func (q *Queries) DeleteShow(ctx context.Context, internalShowID string) (string, error) {
	row := q.db.QueryRow(ctx, deleteShow, internalShowID)
	var deletedID string
	err := row.Scan(&deletedID)
	return deletedID, err
}

const getShowByID = `-- name: GetShowByID :one
SELECT
  internal_show_id,
  title_preferred,
  title_original,
  alt_titles,
  type,
  status,
  synopsis,
  start_date,
  end_date,
  poster_url,
  banner_url,
  season_count,
  episode_count,
  external_ids,
  created_at,
  updated_at
FROM shows
WHERE internal_show_id = $1::uuid
LIMIT 1
`

func (q *Queries) GetShowByID(ctx context.Context, internalShowID string) (Show, error) {
	row := q.db.QueryRow(ctx, getShowByID, internalShowID)
	var i Show
	err := row.Scan(
		&i.InternalShowID,
		&i.TitlePreferred,
		&i.TitleOriginal,
		&i.AltTitles,
		&i.Type,
		&i.Status,
		&i.Synopsis,
		&i.StartDate,
		&i.EndDate,
		&i.PosterUrl,
		&i.BannerUrl,
		&i.SeasonCount,
		&i.EpisodeCount,
		&i.ExternalIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listShows = `-- name: ListShows :many
SELECT
  internal_show_id,
  title_preferred,
  title_original,
  alt_titles,
  type,
  status,
  synopsis,
  start_date,
  end_date,
  poster_url,
  banner_url,
  season_count,
  episode_count,
  external_ids,
  created_at,
  updated_at
FROM shows
ORDER BY created_at DESC
`

func (q *Queries) ListShows(ctx context.Context) ([]Show, error) {
	rows, err := q.db.Query(ctx, listShows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.InternalShowID,
			&i.TitlePreferred,
			&i.TitleOriginal,
			&i.AltTitles,
			&i.Type,
			&i.Status,
			&i.Synopsis,
			&i.StartDate,
			&i.EndDate,
			&i.PosterUrl,
			&i.BannerUrl,
			&i.SeasonCount,
			&i.EpisodeCount,
			&i.ExternalIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShow = `-- name: UpdateShow :one
UPDATE shows
SET
  title_preferred = $2,
  title_original = $3,
  alt_titles = $4,
  type = $5,
  status = $6,
  synopsis = $7,
  start_date = $8,
  end_date = $9,
  poster_url = $10,
  banner_url = $11,
  season_count = $12,
  episode_count = $13,
  external_ids = $14,
  updated_at = NOW()
WHERE internal_show_id = $1::uuid
RETURNING
  internal_show_id,
  title_preferred,
  title_original,
  alt_titles,
  type,
  status,
  synopsis,
  start_date,
  end_date,
  poster_url,
  banner_url,
  season_count,
  episode_count,
  external_ids,
  created_at,
  updated_at
`

type UpdateShowParams struct {
	InternalShowID string
	TitlePreferred string
	TitleOriginal  *string
	AltTitles      []string
	Type           string
	Status         string
	Synopsis       *string
	StartDate      *string
	EndDate        *string
	PosterUrl      *string
	BannerUrl      *string
	SeasonCount    *int64
	EpisodeCount   *int64
	ExternalIds    []byte
}

func (q *Queries) UpdateShow(ctx context.Context, arg UpdateShowParams) (Show, error) {
	row := q.db.QueryRow(ctx, updateShow,
		arg.InternalShowID,
		arg.TitlePreferred,
		arg.TitleOriginal,
		arg.AltTitles,
		arg.Type,
		arg.Status,
		arg.Synopsis,
		arg.StartDate,
		arg.EndDate,
		arg.PosterUrl,
		arg.BannerUrl,
		arg.SeasonCount,
		arg.EpisodeCount,
		arg.ExternalIds,
	)
	var i Show
	err := row.Scan(
		&i.InternalShowID,
		&i.TitlePreferred,
		&i.TitleOriginal,
		&i.AltTitles,
		&i.Type,
		&i.Status,
		&i.Synopsis,
		&i.StartDate,
		&i.EndDate,
		&i.PosterUrl,
		&i.BannerUrl,
		&i.SeasonCount,
		&i.EpisodeCount,
		&i.ExternalIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
